# 테스트 환경용 포트 번호 설정
myprop.port=8080
# 테스트 환경용 사용자 이름 설정
myprop.username=테스터
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/lab_db
spring.datasource.username=lab
spring.datasource.password=lab
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
logging.level.com.rookies6.myspringbootlab=DEBUG
spring.jpa.hibernate.ddl-auto=update